/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loadoutgenerator;

/**
 *
 * @author samanthahohmann
 */
public class LoadoutGenerator extends javax.swing.JFrame {

    /**
     * Creates new form LoadoutGenerator
     */
    public LoadoutGenerator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pleaseCheckClass = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        scout = new javax.swing.JCheckBox();
        soldier = new javax.swing.JCheckBox();
        pyro = new javax.swing.JCheckBox();
        demoman = new javax.swing.JCheckBox();
        heavy = new javax.swing.JCheckBox();
        engineer = new javax.swing.JCheckBox();
        medic = new javax.swing.JCheckBox();
        sniper = new javax.swing.JCheckBox();
        spy = new javax.swing.JCheckBox();
        className = new javax.swing.JLabel();
        primary = new javax.swing.JLabel();
        secondary = new javax.swing.JLabel();
        melee = new javax.swing.JLabel();
        pda = new javax.swing.JLabel();
        generate = new javax.swing.JButton();

        pleaseCheckClass.setTitle("Oops!");
        pleaseCheckClass.setPreferredSize(new java.awt.Dimension(300, 100));
        pleaseCheckClass.setSize(new java.awt.Dimension(400, 100));

        jLabel1.setText("Please specify at least one class.");
        jLabel1.setPreferredSize(new java.awt.Dimension(399, 16));

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pleaseCheckClassLayout = new javax.swing.GroupLayout(pleaseCheckClass.getContentPane());
        pleaseCheckClass.getContentPane().setLayout(pleaseCheckClassLayout);
        pleaseCheckClassLayout.setHorizontalGroup(
            pleaseCheckClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pleaseCheckClassLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pleaseCheckClassLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
        pleaseCheckClassLayout.setVerticalGroup(
            pleaseCheckClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pleaseCheckClassLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TF2 Loadout Generator");

        scout.setSelected(true);
        scout.setText("Scout");
        scout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoutActionPerformed(evt);
            }
        });

        soldier.setSelected(true);
        soldier.setText("Soldier");
        soldier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soldierActionPerformed(evt);
            }
        });

        pyro.setSelected(true);
        pyro.setText("Pyro");
        pyro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pyroActionPerformed(evt);
            }
        });

        demoman.setSelected(true);
        demoman.setText("Demoman");
        demoman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                demomanActionPerformed(evt);
            }
        });

        heavy.setSelected(true);
        heavy.setText("Heavy");
        heavy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heavyActionPerformed(evt);
            }
        });

        engineer.setSelected(true);
        engineer.setText("Engineer");
        engineer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                engineerActionPerformed(evt);
            }
        });

        medic.setSelected(true);
        medic.setText("Medic");
        medic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicActionPerformed(evt);
            }
        });

        sniper.setSelected(true);
        sniper.setText("Sniper");
        sniper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sniperActionPerformed(evt);
            }
        });

        spy.setSelected(true);
        spy.setText("Spy");
        spy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spyActionPerformed(evt);
            }
        });

        className.setText("Class:");

        primary.setText("Primary Weapon");

        secondary.setText("Secondary Weapon");

        melee.setText("Melee Weapon");

        pda.setText("PDA");

        generate.setText("Generate");
        generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pyro)
                    .addComponent(soldier)
                    .addComponent(scout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(className)
                    .addComponent(generate)
                    .addComponent(pda)
                    .addComponent(melee)
                    .addComponent(secondary)
                    .addComponent(primary)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(engineer)
                            .addComponent(heavy)
                            .addComponent(demoman))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(medic)
                            .addComponent(sniper)
                            .addComponent(spy))))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(className)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(primary)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(secondary)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(melee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pda)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scout)
                    .addComponent(demoman)
                    .addComponent(medic))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soldier)
                    .addComponent(heavy)
                    .addComponent(sniper))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pyro)
                    .addComponent(engineer)
                    .addComponent(spy))
                .addGap(18, 18, 18)
                .addComponent(generate)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void scoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoutActionPerformed
        LoadoutGeneratorHandler.toggleEnabled(0);
    }//GEN-LAST:event_scoutActionPerformed

    private void soldierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soldierActionPerformed
        LoadoutGeneratorHandler.toggleEnabled(1);
    }//GEN-LAST:event_soldierActionPerformed

    private void pyroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pyroActionPerformed
        LoadoutGeneratorHandler.toggleEnabled(2);
    }//GEN-LAST:event_pyroActionPerformed

    private void demomanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_demomanActionPerformed
        LoadoutGeneratorHandler.toggleEnabled(3);
    }//GEN-LAST:event_demomanActionPerformed

    private void heavyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heavyActionPerformed
        LoadoutGeneratorHandler.toggleEnabled(4);
    }//GEN-LAST:event_heavyActionPerformed

    private void engineerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_engineerActionPerformed
        LoadoutGeneratorHandler.toggleEnabled(5);
    }//GEN-LAST:event_engineerActionPerformed

    private void medicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicActionPerformed
        LoadoutGeneratorHandler.toggleEnabled(6);
    }//GEN-LAST:event_medicActionPerformed

    private void sniperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sniperActionPerformed
        LoadoutGeneratorHandler.toggleEnabled(7);
    }//GEN-LAST:event_sniperActionPerformed

    private void spyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spyActionPerformed
        LoadoutGeneratorHandler.toggleEnabled(8);
    }//GEN-LAST:event_spyActionPerformed

    private void generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateActionPerformed
        boolean anythingEnabled = false;
        for(int i = 0; i < LoadoutGeneratorHandler.enabled.length; i++)
        {
            if(LoadoutGeneratorHandler.enabled[i])
            {
                anythingEnabled = true;
            }
        }
        if(!anythingEnabled)
        {
            pleaseCheckClass.setVisible(true);
        }
        else
        {
            Loadout l = LoadoutGeneratorHandler.generate();
            className.setText(l.getClassName() + ":");
            primary.setText(l.getPrimary());
            secondary.setText(l.getSecondary());
            melee.setText(l.getMelee());
            pda.setText(l.getPDA());
        }
        
    }//GEN-LAST:event_generateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        pleaseCheckClass.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadoutGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadoutGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadoutGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadoutGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoadoutGeneratorHandler.load();
                new LoadoutGenerator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel className;
    private javax.swing.JCheckBox demoman;
    private javax.swing.JCheckBox engineer;
    private javax.swing.JButton generate;
    private javax.swing.JCheckBox heavy;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox medic;
    private javax.swing.JLabel melee;
    private javax.swing.JLabel pda;
    private javax.swing.JDialog pleaseCheckClass;
    private javax.swing.JLabel primary;
    private javax.swing.JCheckBox pyro;
    private javax.swing.JCheckBox scout;
    private javax.swing.JLabel secondary;
    private javax.swing.JCheckBox sniper;
    private javax.swing.JCheckBox soldier;
    private javax.swing.JCheckBox spy;
    // End of variables declaration//GEN-END:variables
}
